# Generated by Django 3.2 on 2022-08-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='used_welcome_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
