# Generated by Django 3.2 on 2022-08-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_used_welcome_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='used_welcome_coupon',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
