# Generated by Django 3.2 on 2022-07-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_alter_systempreference_data_type'),
        ('artworks', '0002_auto_20220729_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=254)),
                ('on_sale', models.BooleanField(blank=True, default=False, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('art_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.artstyle')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.artgenre')),
                ('sale_percentage', models.ForeignKey(blank=True, default='S', null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.systempreference')),
            ],
        ),
    ]
