# Generated by Django 3.2 on 2022-07-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_alter_systempreference_data_type'),
        ('artworks', '0003_artworks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artworks',
            new_name='Artwork',
        ),
    ]
