# Generated by Django 3.2 on 2022-07-31 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_rename_art_style_artwork_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
