# Generated by Django 3.2 on 2022-08-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_auto_20220802_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='artframe',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
