# Generated by Django 3.2 on 2022-08-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='artwork_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='frame_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
