# Generated by Django 3.2 on 2022-08-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_used_welcome_coupon'),
        ('checkout', '0002_auto_20220808_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('code', models.CharField(default='O', max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_for', to='profiles.userprofile')),
            ],
        ),
    ]
