# Generated by Django 3.2 on 2022-08-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_notification_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, default='O', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status', to='checkout.orderstatus'),
        ),
    ]
