# Generated by Django 3.2 on 2022-08-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='review_comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
