# Generated by Django 3.2 on 2022-08-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(choices=[('0', '0'), (1, 'One star'), (2, 'Two star'), (3, 'Three star'), (4, 'Four star'), (5, 'Five star')], default='0'),
        ),
    ]
