# Generated by Django 3.2 on 2022-08-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('explanation', models.TextField()),
                ('last_view_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
