# Generated by Django 3.2 on 2022-07-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMessage',
            fields=[
                ('code', models.CharField(choices=[('T', 'Terms of Use'), ('P', 'Privacy Policy'), ('A', 'About Us'), ('H', 'Home Welcome Message')], max_length=1, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemPreference',
            fields=[
                ('code', models.CharField(choices=[('S', 'Sales Percentage'), ('D', 'Description of Current Sales'), ('R', 'Return Valid Days')], default='S', max_length=1, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=3)),
            ],
        ),
    ]
