# Generated by Django 3.2 on 2022-07-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempreference',
            name='data_type',
            field=models.CharField(choices=[('str', 'Text'), ('int', 'Integer')], max_length=3),
        ),
    ]
