# Generated by Django 3.2 on 2022-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_alter_systempreference_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempreference',
            name='code',
            field=models.CharField(choices=[('S', 'Sales Percentage'), ('D', 'Description of Current Sales'), ('R', 'Return Valid Days'), ('Q', 'Maximum Customer Selectable Quantity')], default='S', max_length=2, primary_key=True, serialize=False),
        ),
    ]
