# Generated by Django 3.2 on 2022-08-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_alter_systempreference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempreference',
            name='code',
            field=models.CharField(choices=[('S', 'Sales Percentage'), ('D', 'Description of Current Sales'), ('R', 'Return Valid Days'), ('Q', 'Maximum Customer Selectable Quantity'), ('CF', 'Customer welcome Coupon Code'), ('CR', 'Customer Threshold Coupon Code'), ('C1', 'Welcome coupon percentage discount'), ('T1', 'Threshold Amount'), ('C2', 'Threshold discount percentage')], default='S', max_length=2, primary_key=True, serialize=False),
        ),
    ]
